"""Initial migration after reset

Revision ID: 1d90be82dc85
Revises: 
Create Date: 2024-11-28 22:37:54.882340

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1d90be82dc85"
down_revision = "e4d3b5b664e4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_blocklist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=250), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("jti"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("activated", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("activated")

    op.drop_table("token_blocklist")
    # ### end Alembic commands ###
