"""empty message

Revision ID: 246e936af0c0
Revises: 25dc9f369626
Create Date: 2024-11-18 12:14:40.517570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '246e936af0c0'
down_revision = '25dc9f369626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_manager_id', 'employees', ['manager_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_manager_id', type_='foreignkey')

    # ### end Alembic commands ###
